### ISSUE TITLE
read sol file highs

### ISSUE THREAD

**Issue by rizky-r-lab** [PyPSA/PyPSA#562] opened 2023-02-16 01:54 UTC
i appreciate that you have highs interface now. However, i found error when reading sol file of highs solver. The sol file itself found the objective function as shown in figure below
![image](https://user-images.githubusercontent.com/76988293/219245915-7f8d9c28-b620-4499-a61e-5d91cab1571f.png)

However reading the file, it became like this
![image](https://user-images.githubusercontent.com/76988293/219246158-264f1cf7-e8d2-4d2f-b2d1-0229c18b9f12.png)

So,  error occured
`Unable to parse string "e-12" at position 871847`

I think it is due to pd.read_fwf in highs solver. Because the default it's just read 100  rows letting the parser determine the colspecs.

**Comment by FabianHofmann** [comment] 2023-02-16 08:46
thanks for reporting @rizky-r-lab. The native optimization framework is not continuously tested. I would propose to use `n.optimize(solver_name='highs')` instead of `n.lopf(...)`. As for the bug, perhaps @pz-max has a quick solution?

**Comment by rizky-r-lab** [comment] 2023-02-16 09:29
i have tried `n.optimize(solver_name='highs')` and  `n.optimize(solver_name='cbc')`. I don't know why, but my jupyter crash. However if i use `n.lopf('solver_name='cbc)`, it show the result.

**Comment by pz-max** [comment] 2023-02-16 13:57
@rizky-r-lab which highs solver version do you use? I tested it only for one specific version. 

@FabianHofmann I would suggest we deprecate the n.lopf highs integration in favour of the well tested Linopy version. I will do this & also add an logger to notify the supported highs version for the deprecated highs interface

**Comment by rizky-r-lab** [comment] 2023-02-16 14:09
@pz-max , in my laptop, i am using highs 1.3.1, while in my desktop i am using 1.1.1.  Both failed.

Currently i am quick fix this using `sol = pd.read_csv(io.BytesIO(trimed_sol_fn), skiprows = [0], sep = r"\s+", engine="python")`  in run_and _read_highs function.

**Comment by pz-max** [comment] 2023-02-16 14:19
@rizky-r-lab great that you found a fix. Do you think the PyPSA example will still be solvable with the quick fix? In case, yes maybe it's worth doing a PR?

@FabianHofmann please let me know if we should continue with the depreciation of this function (as I described above).

**Comment by rizky-r-lab** [comment] 2023-02-16 14:25
I am not yet tested it, however it think it will still solvable

**Comment by pz-max** [comment] 2023-02-16 14:36
I think if we deprecate highs Interfaxe within lopf (waiting for Fabian's approval), it is probably not worth adding the fix.

In case it's worth adding the fix it would be useful if you can share a example of the minimal network test, as well as instructions what to do to reproduce your test (e.g 1. install highs according to this description, 2. add the fix in this function, 3. execute the tests with xxx). Let's wait for Fabian for now.

**Comment by fneum** [comment] 2023-07-23 08:46
Happy to include a PR that fixes the `linopf` HiGHS interface, but since it has been deprecated, we won't fix it.

**Closed by fneum** 2023-07-23 08:46 UTC
